### ISSUE TITLE
how to use the tools to decompile bytecode to lua files?

### ISSUE THREAD

**Issue by knightowen** [efrederickson/LuaAssemblyTools#1]
Thanks for your code 
I saw
Yes              Decompiler                       Decompiles bytecode to Lua
in README 
but not found how to use it. Could you help me, Thanks very much!

**Comment by efrederickson** [comment]
It doesn't decompile into Lua, it decompiles into LASM, a sort of intermediate language.

Decompiling into LASM can be done like so:
local file = LAT.Lua51.Disassemble(<lua binary string>) -- decompiles binary into mutable chunk
local lasm_string = LAT.Lua51.Decompile.LASM(file) -- converts chunk into LASM code, which is recompilable into binary chunk

**Comment by knightowen** [comment]
Thanks very much!
Is there any tools can decompile lua 5.2's bytecode into lua? or do you have any plan? Just want to make LASM to be easily understood.

**Comment by efrederickson** [comment]
Simply replace the Lua51 namespace with Lua52:
local file = LAT.Lua52.Disassemble

**Comment by knightowen** [comment]
Thanks for quick reply. I mean decompile bytecode into Lua files, not LASM

**Comment by efrederickson** [comment]
That can't be done and I have no plan of creating it, sorry. You might look at unluac and LuaDec, but i don't think they support 5.2

**Comment by knightowen** [comment]
ok, Thanks very much!
