### ISSUE TITLE
Decompile fail

### ISSUE THREAD

**Issue by bentech** [efrederickson/LuaAssemblyTools#2]
Hi I'm getting this error when trying to decompile..

Any ideas why?

C:\lua\lua52.exe: ./src/Lua52\Disassembler.lua:39: IntegerSize cannot be greater
 than SizeT
stack traceback:
        [C]: in function 'error'
        ./src/Lua52\Disassembler.lua:39: in function 'ReadInt32'
        ./src/Lua52\Disassembler.lua:68: in function 'ReadFunction'
        ./src/Lua52\Disassembler.lua:190: in function 'Disassemble'
        ...s\ben\Documents\GitHub\LuaAssemblyTools\Decompiler52.lua:6: in main c
hunk
        [C]: in ?
C:\Users\ben\Documents\GitHub\LuaAssemblyTools [master +1 ~1 -0 !]>

**Comment by efrederickson** [comment]
It looks like it's due to either your platform (although that shouldn't be a problem) or an invalid binary chunk.
