### ISSUE TITLE
LASM file returns the LUA source code?

### ISSUE THREAD

**Issue by bol-Yutti** [efrederickson/LuaAssemblyTools#3]
LASM file returns the LUA source code?
Thank you!

**Comment by efrederickson** [comment]
It does not. You'd have to have a decompiler for that.

**Comment by bol-Yutti** [comment]
LASM decompiler for that.?
Can you give me the related links?
thx

**Comment by efrederickson** [comment]
LuaDec/LuaDec51 - decompiles VM bytecodes back to Lua source.
unluac - A Lua 5.1 decompiler.

From the [Lua wiki](http://lua-users.org/wiki/LuaTools)
